### PR TITLE
Fix license link in README

### PR DESCRIPTION
**Pull request by nonfungible-dev**
Clicking the `GPL 3.0` link resulted in a 404. This PR updates the link to reference the correct repository and fix the broken link!

### CODE REVIEW

**Comment by omarkilani** [comment]
Hey @nonfungible-dev 

Can you please use a relative link?

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes#relative-links-and-image-paths-in-readme-files

Thanks!

**Comment by nonfungible-dev** [comment]
Great suggestion, @omarkilani! Implemented 👍 

You can verify it works on my branch:
https://github.com/nonfungible-dev/nightmarket-oss/tree/fix-license-link

**Comment by omarkilani** [comment]
@nonfungible-dev I think you can just do `LICENSE` instead of `/LICENSE`. 🫡

**Comment by nonfungible-dev** [comment]
Right you are! Apologies for all the back and forth; appreciate your time and patience!

**Pull request merged**
